### ISSUE TITLE
This task uses Node 6 execution handler on SonarCloudPrepare (SonarCloudPrepare)

### ISSUE THREAD

**Issue by franz-ms-muc** [sonarsource-cfamily-examples/windows-cmake-azure-sc#7]
This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**Comment by amelie-renard-sonarsource** [comment]
Thanks @franz-ms-muc for raising the issue. 
The migration has been done and the task now uses Node10.
